---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[rackspace_apt]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: tomcat6
  run_list: ["recipe[rackspace_tomcat]"]
  attributes: {}

- name: tomcat7
  run_list: ["recipe[rackspace_tomcat]"]
  excludes: ["centos-6.4"]
  attributes: {rackspace_tomcat: {base_version: 7}}
